### PR TITLE
don't include suffix in file size, explicit upercase char casting

### PR DESCRIPTION
**Pull request by amfern**
Had problem using dfu-tool, after comparing this file result to dfuse-pack.py, i noticed different header size.

after applying the these PR i could use dfu-tool

### CODE REVIEW

**Comment by majbthrd** [comment]
I appreciate that!  Would you please elaborate on the failure mode you experienced without changing the header size?

The reason I ask is that I am basing the utility on ST's UM0391 Rev 1 (June 2007), which states in Section 2.1:

```
The DFUImageSize field, four-byte coded, presents the total DFU file length in bytes
```

I suppose the name "DFUImageSize" does suggest something other than what their definition says, but it is an information source "straight from the horse's mouth" rather than second-hand from another utility's implementation.

Thanks again!

**Comment by majbthrd** [comment]
Also, in your "correct char upper case casting to binary" you have changed the Target Prefix in byte positions 7 and 11+.  These are mentioned in UM0391, but they are optional fields named "bTargetNamed" and "szTargetName", defined as:

```
The bTargetNamed field is a boolean value which indicates if the target is named or
not.
The szTargetName field gives the target name.
```

What is the failure mode without these?  I ask because I've never heard of this "dfu-tool" until today (I have been using "dfu-util" for years), so I'm trying to understand what the failure modes are.

Thanks!

**Comment by majbthrd** [comment]
I eventually found a Ubuntu system with this installed:

```
$ dfu-tool --version
fwupd 1.2.10
```

I did a series of tests where I programmed a STM32F072 via DFU and then checked the memory via SWD/JTAG to confirm that neither too few nor too many bytes were written.

Without the file_size change, dfu-tool complains:

```
invalid DfuSe image size, got 1053, expected 1037
```

dfu-util accepts both variants with the same operation.  From a specification perspective, I would argue the DFU suffix *is* part of the file size.

Beyond that, even with your proposed changes, dfu-tool just dies:

```
(dfu-tool:1865): FuPluginDfu-WARNING **: 19:54:10.785: DFU version 0x0000 invalid, v1.1 assumed
Writingâ€¦            [-                                                ]cannot download data: [dfuERROR,errFIRMWARE]: endpoint stalled or request not supported

(dfu-tool:1967): FuPluginDfu-WARNING **: 19:58:02.068: DFU version 0x0000 invalid, v1.1 assumed
Writingâ€¦            [-                                                ]cannot download data: [dfuERROR,errFIRMWARE]: endpoint stalled or request not supported

(dfu-tool:2497): FuPluginDfu-WARNING **: 19:59:07.030: DFU version 0x0000 invalid, v1.1 assumed
Writingâ€¦            [-                                                ]cannot download data: [dfuERROR,errFIRMWARE]: endpoint stalled or request not supported
```

I tried downloading the latest [dfu-tool code](https://github.com/fwupd/fwupd/), but that project is an utter nightmare to try to compile.  A pet peeve of mine are projects that require downloading a spectrum of extra tools to make building "easier".

**Comment by amfern** [comment]
i had made some changes to the dfu-tool before it could work with stm32 https://github.com/fwupd/fwupd/pull/1944
i used dfu-utils and works fine except its really slow, dfu-tool is much faster at flashing.

I was too quick to judge, the firmware does flash, but the controller doesn't boot after restart.
comparing dfuse file created by dfuse-pack.py(left column) from ihex file to dfu files generated by elf2dfuse(right column) there still some diff.

```
00000122 D8 C8
00000123 02 01
000002EE F4 D0
000002EF B1 01
000002F0 04 00
000002F1 00 08
000002F2 01 08
000002F3 00 01
000598DF 00 FF
000598E0 00 FF
000598EB 2C 60
000598EC 25 98
000598ED 4A 77
000598EE C6 CB
```

i use this command line to compare 
```
cmp -l obj/xtend_fcos_2.2.0-RC3_KAKUTEF7-2.dfu obj/xtend_fcos_2.2.0-RC3_KAKUTEF7.dfu | gawk '{printf "%08X %02X %02X\n", $1, strtonum(0$2), strto
num(0$3)}'
```


btw flashing using the ihex dfuse works both with dfu-utils and dfu-tool, flashing the dfu generated from elf works only with dfu-utils

**Comment by amfern** [comment]
> I appreciate that! Would you please elaborate on the failure mode you experienced without changing the header size?
> 
> The reason I ask is that I am basing the utility on ST's UM0391 Rev 1 (June 2007), which states in Section 2.1:
> 
> ```
> The DFUImageSize field, four-byte coded, presents the total DFU file length in bytes
> ```
> 
> I suppose the name "DFUImageSize" does suggest something other than what their definition says, but it is an information source "straight from the horse's mouth" rather than second-hand from another utility's implementation.
> 
> Thanks again!

i see maybe i should change the dfu-tool instead, altough looking at pack-dfuse.py from dfu-util repo, in this line IIUC the header size isn't included in the file size https://github.com/kiibohd/dfu-util/blob/75da79608881da244f28a071b9a195d07197905b/dfuse-pack.py#L85

**Comment by amfern** [comment]
> Also, in your "correct char upper case casting to binary" you have changed the Target Prefix in byte positions 7 and 11+. These are mentioned in UM0391, but they are optional fields named "bTargetNamed" and "szTargetName", defined as:
> 
> ```
> The bTargetNamed field is a boolean value which indicates if the target is named or
> not.
> The szTargetName field gives the target name.
> ```
> 
> What is the failure mode without these? I ask because I've never heard of this "dfu-tool" until today (I have been using "dfu-util" for years), so I'm trying to understand what the failure modes are.
> 
> Thanks!

there is no failure, i just wanted to align my self with pack-dfuse.py, so i would see less diff when comparing both binaries

**Comment by majbthrd** [comment]
Am I correctly understanding you to be saying that: even after your tweaks to elf2dfuse to make it emulate “dfuse-pack.py”, the two .dfu files differ in the bytes you indicated?

It is highly problematic for me to diagnose what bytes are wrong when I don’t know what those bytes correspond to.  I am assuming that it has something to do with decoding the ELF sections (and has nothing to do with the DFU headers).

Just to summarize to maintain some semblance of sanity, I think the ongoing issues are:

1) You made a series of changes to elf2dfuse to make it emulate “dfuse-pack.py”:
a) casting of chars to uint8_t
b) change file_size value
c) addition of optional target string
and it is unclear which of these changes were strictly needed.
2) dfu-tool needed modifications to work
3) the image contained in the .dfu produced by elf2dfuse is different from “dfuse-pack.py” and the target doesn’t run

Would you agree?

I’m OK with 1(a) (more modern compilers complain about this) and 1(b) (it doesn’t harm dfu-util behavior, although I would like to update the comment to explain why this value disagrees with the specification).  Unless 1(c) provides utility, I would rather omit it.

On 3, as I say, more debugging is needed to determine the difference in behavior between “dfuse-pack.py” and elf2dfuse.

**Comment by amfern** [comment]
yes, you right, thank you for making sense out of all of this.
I update the PR to reflect your suggestions, only include changes (a) and (b), omitted change (c) from this PR.
on change (b) my comment is purely a guess based on the RFC and this commit https://github.com/Stefan-Schmidt/dfu-util/commit/861a14f7af7f8b5212ca5b4f2b99ee991fec5e81

**Comment by majbthrd** [comment]
Thanks @amfern!  I appreciate your patience; I've merged the PR.  I would like to understand why the elf translation is not happening the same as “dfuse-pack.py”.  Is there a sample .elf that you could make publicly available?

**Comment by amfern** [comment]
Thank you for doing the bulk of the work, figuring out how to read elf file and generate dfu file from it, so I don't have to use some python scripts. I very appreciate this project

**Pull request merged**
